//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practicee7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer_history
    {
        public int Id { get; set; }
        public int Day { get; set; }
        public int Part_needed { get; set; }
        public decimal Repair_price { get; set; }
        public string Status { get; set; }
        public decimal Earnings { get; set; }
    
        public virtual Parts Parts { get; set; }
    }
}
