//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practicee7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_orders
    {
        public int Id { get; set; }
        public int Part_id { get; set; }
        public int Quantity { get; set; }
        public int Delivery_in { get; set; }
        public Nullable<System.DateTime> Created_at { get; set; }
    
        public virtual Parts Parts { get; set; }
    }
}
